### PR TITLE
QTCreator-less build instructions

### PR DESCRIPTION
**Pull request by sudocurse**
I didn't want to install with a gui so I got cross-compilation working with just the toolchain and some basic dependencies. It should help with automating the build. Unfortunately deploying is not automated yet, but this seems pretty trivial to do (and this may fit better into https://github.com/dixonary/draft-reMarkable/pull/9)

Adds a table of contents too.

### CODE REVIEW

**Comment by sudocurse** [comment]
these build instructions also work for other apps like https://github.com/dixonary/fingerterm-reMarkable

**Comment by sudocurse** [comment]
This may(?) also help out what https://github.com/dixonary/draft-reMarkable/issues/3 was asking for, and if the deploy step is automated as well, this would address the CI stuff brought up in https://github.com/dixonary/draft-reMarkable/issues/6

**Comment by dixonary** [comment]
This looks great, thanks! I was wondering on a good process for compiling without qtcreator. 

Is it ready to merge or do you want to make any other changes?

**Comment by sudocurse** [comment]
@dixonary  I think it's as good as Im going to get it 😅

**Comment by dixonary** [comment]
Thank you! Hopefully this will help some people :)

**Pull request merged**
