### PR TITLE
Adds build+deploy scripts for non-IDE setup

### PR DESCRIPTION
**Pull request by sudocurse**
Creates scripted build & deploy and adds docs.

Since creating PR #16 I added commits to put draft into the homedir and then link it to the correct locations, based on @Eeems' feedback. (closed that one because some force pushes were making github sad.) Squash on merge please!

### CODE REVIEW

**Comment by dixonary** [comment]
Great! Are you happy for this one to be pushed or do you want to make any further changes?

**Comment by sudocurse** [comment]
@dixonary converted to a draft while I figure out why the systemd unit isn't persisting across reboots

**Comment by dixonary** [comment]
OK, sure :)

Also, can you please add an echoed message to each of the manually-activated scripts to explain what they are going to do? Along with a Y/N confirmation to proceed. That will make me feel a little bit more relaxed about asking people to run these downloaded scripts!

**Comment by Eeems** [comment]
@sudocurse You'll likely want to put the unit file in `/etc/systemd/system` to get it to persist across reboots.

**Comment by sudocurse** [comment]
```
reMarkable: /etc/systemd/system/ systemctl enable draft
Created symlink /etc/systemd/system/multi-user.target.wants/draft.service → /home/root/draft/lib/systemd/system/draft.service.
Created symlink /etc/systemd/system/draft.service → /home/root/draft/lib/systemd/system/draft.service.
```

The issue is that after reboot these files in are missing from `/etc/systemd/system`.

**Comment by Eeems** [comment]
Right, you'll want to place the unit file itself in `/etc/systemd/system`, you can't have the unit files be sourced from `/home/root` unfortunately. I believe it's a timing problem of when the partition is mounted.
```
cp draft.service /etc/systemd/system
systemctl enable draft
```

**Comment by sudocurse** [comment]
Alright, the major steps in each script have a descriptive confirmation dialog that can be preempted by `-y`.  This includes the copying files step, link + start service step, and stop services + unlink step. Added some descriptive text to the usage messages as well.

`draft.service` is now copied to `/lib/systemd/system` rather than linked so it can be sourced on boot and still toggled with `systemctl enable/disable`. Tested a bunch on my device, ready for review and merge

**Review by dixonary — APPROVED** [review]
LGTM. I'll squash & merge. Thanks for all your good work!

**Pull request merged**
